#ifndef _TUSB_CONFIG_H_
#define _TUSB_CONFIG_H_ 1



#define CFG_TUSB_RHPORT0_MODE OPT_MODE_DEVICE
#define CFG_TUD_CDC 1
#define CFG_TUD_CDC_RX_BUFSIZE 256
#define CFG_TUD_CDC_TX_BUFSIZE 256
#define CFG_TUD_VENDOR 0



#endif
